[41기 김승기] Assignment 1 | Westagram Backend Project - Express 초기 환경세팅
wecode-bootcamp-korea/41-backend-westagram-1 pull request #4
Opened 2022-12-20 13:05 UTC by seuungkei

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 데이터베이스 작업
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 - 해당 브랜치(PR)에서 구현하고자 하는 하나의 목표 작성
- email, password를 이용한 로그인 기능 구현 (예시)

<br />

## :: 구현 사항 설명 - 해당 브랜치(PR)에서 작업한 내용 작성
- API 호출 시 필요한 값들에 대한 유효성 검사 (예시)

<br />

## :: 테스트 결과 이미지
1. Server가 잘 동작하는지 확인할 수 있는 Terminal 캡쳐 이미지
2. Postman(Client Tool)을 이용한 API 테스트 결과 이미지
3. DB 작업 PR인 경우 Table 생성 및 수정 결과에 대해 확인할 수 있는 이미지

<br />

## :: 기타 질문 및 특이 사항
- 제가 작성한 함수의 로직이 너무 복잡하다고 생각이 됩니다. 더 효율적인 방법이 없을까요? (예시)

2022-12-21 01:49 UTC, SeongJoon-K requested changes
승기님 ! package.json 파일만 다듬어 주시면 될 거 같습니다! 
리뷰 확인하시고, 꼭 `라벨` 변경해 주세요!

2022-12-21 01:49 UTC, SeongJoon-K commented on seungki/package.json
> +  }
- 프로젝트에서 3rd-party 패키지를 설치해서 사용할 때에는 주의해야 될 사항이 있습니다.
- 해당 패키지가 production 레벨(사용자에게 배포)에서 사용될 패키지인지 local 개발용도로만 사용되는 패키지인지를 알고 있어야 합니다.
- express, mysql, typeorm, dotenv, cors와 같은 패키지는 사용자에게 서비스되는 코드에서는 반드시 포함되어야 하는 라이브러리이므로 package.json 내에 `dependencies`에 포함되어야 합니다.
- 하지만, nodemon과 같은 패키지는 로컬에서 개발할 때, 생산성을 위해서 사용하는 패키지입니다. 그렇기 때문에 이는 `devDependencies`에 추가 혹은 `global 환경`에 설치해서 사용할 수 있도록 만들어주세요.
- mysql & mysql2 드라이버 패키지는 서로 동일한 기능을 하는 패키지 입니다. 따라서 둘 중 하나를 선택하여 설치를 진행해주세요.

2022-12-21 07:13 UTC, seuungkei commented on seungki/package.json
> +  }
수정 완료했습니다!

2022-12-21 07:36 UTC, SeongJoon-K requested changes
승기님 ! initial setting 과제 너무 잘 해주셨습니다 !
import 순서 변경과 주석 제거 후 다시 push 해 주세요 !

2022-12-21 07:36 UTC, SeongJoon-K commented on seungki/app.js
> +dotenv.config()
- mport 순서 컨벤션에 맞게 수정해주세요! 사소한 부분이라 놓치기 쉽지만 처음 코드를 작성할 때부터 신경쓰고 작성하게 되면 추후에 관리하기도 용이하며 가독성도 좋아집니다.
- 다음과 같은 순서로 import 해줍니다.
```suggestion
//// Built-in package
const http = require('http')

//// 3rd-party package
require('dotenv').config();
const express = require('express');
const cors    = require('cors');
const morgan  = require('morgan');
const { DataSource } = require('typeorm');

//custom package
const api = require('./../api')

const app = express();

2022-12-21 07:49 UTC, seuungkei commented on seungki/app.js
> +dotenv.config()
순서 컨벤션과 주석 수정 완료하였습니다!

2022-12-22 01:17 UTC, SeongJoon-K approved these changes

2022-12-22 01:17 UTC, merged